server:
  port: 8081
spring:
  application:
    name: "userService"
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "users"
    description: "Bitrate Users Application"
    version: "1.0.0"

logging:
  level:
    com:
      bitrate:
        userService: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A713474376B2B